### ISSUE TITLE
Submitting more context in requests, limiting completion length/end

### ISSUE THREAD

**Issue by ErikBjare** [mzbac/wizardCoder-vsc#1]
Just read the article, excited for this!

I have yet to try it, but I assume there is a way to get context after the cursor into the request (and even context from the rest of the project), and that would be pretty cool.

Edit: I see you already send the context after the cursor! Nice :)

Also, going even further, it should be possible to fix the issue of over-completing closing braces for many cases.

Looking forward to try this soon!

Also, you may want to link the article in the README: https://medium.com/@anchen.li/build-your-own-copliot-using-open-source-llm-ff9da556cb09

**Comment by mzbac** [comment]
Yeah, I quickly tested it after using the prompt format to fill in the middle. The closing tag issue seems to be fixed.

**Comment by mzbac** [comment]
@ErikBjare, I will close the issue for now. Feel free to reopen it if you still have any issues.
