### ISSUE TITLE
response is not showing at the chat panel

### ISSUE THREAD

**Issue by d5423197** [mzbac/wizardCoder-vsc#6]
Hello there,

Thanks a lot for sharing such a great project with us.

I am trying to use your framework. I have built the server. 

If I input some simple question, when the answer is short, it will show up in the chat panel.

But if I input some difficult question (the answer is long), the response will not show up (I saw the response at the server end)

![1699004396159](https://github.com/mzbac/wizardCoder-vsc/assets/61330860/9a762938-7d77-4a53-bcab-3ef22af01c5d)

Any help will be appreciated!

Thanks,

ZD

**Comment by mzbac** [comment]
Hi @d5423197,
I suspect that somehow your server is erroring out for the long response. Feel free to folk the repo and debug the code here.                        https://github.com/mzbac/wizardCoder-vsc/blob/7a7c362d558118d29e5b066e2dc05f792cfa046b/src/chatWithWizardCoder.ts#L62-L79

**Comment by d5423197** [comment]
Hi there,

Thanks for your reply. I do not know ts.... 

BTW, I can see the output from my server end. I just do not see it on the front panel.

Is there any way I can see the ts error message in VsCode.

Thanks,

ZD
